services:
  - type: web
    name: parcelscraper
    env: node
    plan: free
    autoDeploy: true
    buildCommand: npm ci && npm run build
    startCommand: node server.cjs
    envVars:
      - key: NODE_VERSION
        value: 20.19.1

